export const Products = [
    {
        id: 1,
        title: "Grapes",
        image: "/img/fruite-item-5.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$40000.99",
        category: "Fruits",
        artist: "Artist1",
        size: ['S', 'M', 'L'],
        orientation: ["Square", "Portrait", "LandScape", "Round"],
        color: "Green"
    },
    {
        id: 2,
        title: "Grapes",
        image: "/img/fruite-item-5.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$70000.99",
        category: "Vegetables",
        artist: "Artist1",
        size: ['S','L'],
        orientation: ["Square", "Portrait"],
        color: "Green"
    },
    {
        id: 3,
        title: "Raspberries",
        image: "/img/fruite-item-2.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$50000.99",
        category: "Fruits",
        artist: "Artist4",
        size: ['M'],
        orientation: ["Portrait", "Round"],
        color: "Red"
    },
    {
        id: 4,
        title: "Apricots",
        image: "/img/fruite-item-4.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$100000.99",
        category: "Fruits",
        artist: "Artist2",
        size: ['S','L'],
        orientation: ["Square", "LandScape", "Round"],
        color: "Brown"
    },
    {
        id: 5,
        title: "Banana",
        image: "/img/fruite-item-3.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$50000.99",
        category: "DryFruits",
        artist: "Artist3",
        size: ['L'],
        orientation: ["Square"],
        color: "Yellow"
    },
    {
        id: 6,
        title: "Oranges",
        image: "/img/fruite-item-1.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$40000.99",
        category: "Vegetables",
        artist: "Artist4",
        size: ['S', 'M', 'L'],
        orientation: ["LandScape", "Round"],
        color: "Orange"
    },
    {
        id: 7,
        title: "Raspberries",
        image: "/img/fruite-item-2.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$100000.99",
        category: "DryFruits",
        artist: "Artist2",
        size: ['S', 'M'],
        orientation: ["Round"],
        color: "Red"
    },
    {
        id: 8,
        title: "Grapes",
        image: "/img/fruite-item-5.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$20000.99",
        category: "Fruits",
        artist: "Artist2",
        size: ['L'],
        orientation: ["Square","Round"],
        color: "Green"
    },
    {
        id: 9,
        title: "Oranges",
        image: "/img/fruite-item-1.jpg",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit sed do eiusmod te incididunt",
        price: "$60000.99",
        category: "Vegetables",
        artist: "Artist1",
        size: ['S', 'M', 'L'],
        orientation: ["Square"],
        color: "Orange"
    },
]