

import "./style.css"
import { Providers } from "@/redux/Provider";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

import 'bootstrap/dist/css/bootstrap.min.css'
import Header from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import('bootstrap/dist/js/bootstrap.min.js')


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Raleway:wght@600;800&display=swap" rel="stylesheet" />

        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />

        <link href="/lib/lightbox/css/lightbox.min.css" rel="stylesheet" />
        <link href="/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />
      </head>
      <body>
        <Providers>
          <ToastContainer />
          <Header />
          {children}
          <Footer />
        </Providers>
        <script src="/lib/easing/easing.min.js"></script>
        <script src="/lib/waypoints/waypoints.min.js"></script>
        <script src="/lib/lightbox/js/lightbox.min.js"></script>
        <script src="/lib/owlcarousel/owl.carousel.min.js"></script>
      </body>
    </html>
  );
}
